// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBefMAZEnkdUBVLrBP_8rbObqDwaVZlBR0',
    appId: '1:175937838374:web:cdae420bbab6b6b3caf5e7',
    messagingSenderId: '175937838374',
    projectId: 'apporder-9a092',
    authDomain: 'apporder-9a092.firebaseapp.com',
    storageBucket: 'apporder-9a092.firebasestorage.app',
    measurementId: 'G-Y0JS4P6ES2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxArKcstLfe1vzqCBbH1cVSRKN9lOfps0',
    appId: '1:175937838374:android:2257a70af79158fecaf5e7',
    messagingSenderId: '175937838374',
    projectId: 'apporder-9a092',
    storageBucket: 'apporder-9a092.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfNOquw-R5LiXM6kuws3QjT00x610jbAs',
    appId: '1:175937838374:ios:67eb949045492b0dcaf5e7',
    messagingSenderId: '175937838374',
    projectId: 'apporder-9a092',
    storageBucket: 'apporder-9a092.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfNOquw-R5LiXM6kuws3QjT00x610jbAs',
    appId: '1:175937838374:ios:67eb949045492b0dcaf5e7',
    messagingSenderId: '175937838374',
    projectId: 'apporder-9a092',
    storageBucket: 'apporder-9a092.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBefMAZEnkdUBVLrBP_8rbObqDwaVZlBR0',
    appId: '1:175937838374:web:611b0dd6fe1f6589caf5e7',
    messagingSenderId: '175937838374',
    projectId: 'apporder-9a092',
    authDomain: 'apporder-9a092.firebaseapp.com',
    storageBucket: 'apporder-9a092.firebasestorage.app',
    measurementId: 'G-GG7HT6MSZH',
  );
}
